"""CliRunner-level tests for the requirements command group."""

import pytest
from click.testing import CliRunner

from odoodev.cli import cli


@pytest.fixture
def env(tmp_path, monkeypatch):
    """A version config pointing at tmp_path, with a controllable baseline."""
    base_file = tmp_path / "requirements.base.txt"
    base_file.write_text("Babel==2.16.0\nWerkzeug==3.1.3\n", encoding="utf-8")
    monkeypatch.setattr(
        "odoodev.core.requirements_sync.get_base_requirements_path",
        lambda version: base_file,
    )

    class FakePaths:
        native_dir = str(tmp_path)

    class FakeConfig:
        paths = FakePaths()

    monkeypatch.setattr("odoodev.commands.requirements.get_version", lambda version: FakeConfig())
    monkeypatch.setattr("odoodev.commands.requirements.available_versions", lambda: ["16", "18"])
    return tmp_path


def test_sync_writes_the_generated_file(env):
    result = CliRunner().invoke(cli, ["requirements", "sync", "16"])
    assert result.exit_code == 0
    assert "GENERATED by odoodev" in (env / "requirements.txt").read_text(encoding="utf-8")


def test_sync_reports_held_back_pins(env):
    (env / "requirements.local.txt").write_text("Werkzeug==3.0.6\n", encoding="utf-8")
    result = CliRunner().invoke(cli, ["requirements", "sync", "16"])
    assert result.exit_code == 0
    assert "holds" in result.output
    assert "3.1.3" in result.output


def test_sync_check_exits_1_when_stale_and_writes_nothing(env):
    result = CliRunner().invoke(cli, ["requirements", "sync", "16", "--check"])
    assert result.exit_code == 1
    assert not (env / "requirements.txt").exists()


def test_sync_check_exits_0_when_current(env):
    CliRunner().invoke(cli, ["requirements", "sync", "16"])
    result = CliRunner().invoke(cli, ["requirements", "sync", "16", "--check"])
    assert result.exit_code == 0


def test_sync_blocked_exits_1_and_keeps_the_file(env):
    (env / "requirements.txt").write_text("hand written\n", encoding="utf-8")
    result = CliRunner().invoke(cli, ["requirements", "sync", "16"])
    assert result.exit_code == 1
    assert "adopt" in result.output
    assert (env / "requirements.txt").read_text(encoding="utf-8") == "hand written\n"


def test_sync_all_covers_every_configured_version(env):
    result = CliRunner().invoke(cli, ["requirements", "sync", "--all"])
    assert result.exit_code == 0
    assert "v16" in result.output
    assert "v18" in result.output


def test_diff_json_contract(env, monkeypatch):
    import json

    (env / "requirements.local.txt").write_text("Werkzeug==3.0.6\n", encoding="utf-8")
    monkeypatch.setattr(
        "odoodev.core.requirements_sync.installed_packages",
        lambda venv_dir: {"werkzeug": "3.0.6"},
    )
    result = CliRunner().invoke(cli, ["requirements", "diff", "16", "--json"])
    assert result.exit_code == 0
    payload = json.loads(result.output.strip())
    assert payload["version"] == "16"
    names = {row["name"]: row for row in payload["rows"]}
    assert names["Werkzeug"]["status"] == "local override"


def test_diff_never_writes(env):
    CliRunner().invoke(cli, ["requirements", "diff", "16"])
    assert not (env / "requirements.txt").exists()


def test_adopt_moves_local_only_entries_and_asks_about_conflicts(env, monkeypatch):
    (env / "requirements.txt").write_text("Babel==2.16.0\nWerkzeug==3.0.6\nmsal==1.31.0\n", encoding="utf-8")
    monkeypatch.setattr("odoodev.commands.requirements.select", lambda message, choices: "keep local")

    result = CliRunner().invoke(cli, ["requirements", "adopt", "16"])
    assert result.exit_code == 0

    overlay = (env / "requirements.local.txt").read_text(encoding="utf-8")
    assert "Werkzeug==3.0.6" in overlay
    assert "msal==1.31.0" in overlay
    assert "Babel" not in overlay
    assert (env / "requirements.txt.pre-adopt").exists()
    assert "GENERATED by odoodev" in (env / "requirements.txt").read_text(encoding="utf-8")


def test_adopt_taking_the_baseline_leaves_it_out_of_the_overlay(env, monkeypatch):
    (env / "requirements.txt").write_text("Werkzeug==3.0.6\n", encoding="utf-8")
    monkeypatch.setattr("odoodev.commands.requirements.select", lambda message, choices: "take baseline")

    CliRunner().invoke(cli, ["requirements", "adopt", "16"])
    overlay = (env / "requirements.local.txt").read_text(encoding="utf-8")
    assert "Werkzeug" not in overlay
    assert "Werkzeug==3.1.3" in (env / "requirements.txt").read_text(encoding="utf-8")


def test_adopt_yes_keeps_every_local_entry_without_prompting(env):
    (env / "requirements.txt").write_text("Werkzeug==3.0.6\nmsal==1.31.0\n", encoding="utf-8")
    result = CliRunner().invoke(cli, ["requirements", "adopt", "16", "--yes"])
    assert result.exit_code == 0
    overlay = (env / "requirements.local.txt").read_text(encoding="utf-8")
    assert "Werkzeug==3.0.6" in overlay
    assert "msal==1.31.0" in overlay


def test_adopt_refuses_on_an_already_generated_file(env):
    CliRunner().invoke(cli, ["requirements", "sync", "16"])
    result = CliRunner().invoke(cli, ["requirements", "adopt", "16"])
    assert result.exit_code == 1
    assert "already" in result.output.lower()
