"""CliRunner-level tests for the requirements command group."""

import pytest
from click.testing import CliRunner

from odoodev.cli import cli


@pytest.fixture
def env(tmp_path, monkeypatch):
    """A version config pointing at tmp_path, with a controllable baseline."""
    base_file = tmp_path / "requirements.base.txt"
    base_file.write_text("Babel==2.16.0\nWerkzeug==3.1.3\n", encoding="utf-8")
    monkeypatch.setattr(
        "odoodev.core.requirements_sync.get_base_requirements_path",
        lambda version: base_file,
    )

    class FakePaths:
        native_dir = str(tmp_path)

    class FakeConfig:
        paths = FakePaths()

    monkeypatch.setattr("odoodev.commands.requirements.get_version", lambda version: FakeConfig())
    monkeypatch.setattr("odoodev.commands.requirements.available_versions", lambda: ["16", "18"])
    return tmp_path


def test_sync_writes_the_generated_file(env):
    result = CliRunner().invoke(cli, ["requirements", "sync", "16"])
    assert result.exit_code == 0
    assert "GENERATED by odoodev" in (env / "requirements.txt").read_text(encoding="utf-8")


def test_sync_reports_held_back_pins(env):
    (env / "requirements.local.txt").write_text("Werkzeug==3.0.6\n", encoding="utf-8")
    result = CliRunner().invoke(cli, ["requirements", "sync", "16"])
    assert result.exit_code == 0
    assert "holds" in result.output
    assert "3.1.3" in result.output


def test_sync_check_exits_1_when_stale_and_writes_nothing(env):
    result = CliRunner().invoke(cli, ["requirements", "sync", "16", "--check"])
    assert result.exit_code == 1
    assert not (env / "requirements.txt").exists()


def test_sync_check_exits_0_when_current(env):
    CliRunner().invoke(cli, ["requirements", "sync", "16"])
    result = CliRunner().invoke(cli, ["requirements", "sync", "16", "--check"])
    assert result.exit_code == 0


def test_sync_blocked_exits_1_and_keeps_the_file(env):
    (env / "requirements.txt").write_text("hand written\n", encoding="utf-8")
    result = CliRunner().invoke(cli, ["requirements", "sync", "16"])
    assert result.exit_code == 1
    assert "adopt" in result.output
    assert (env / "requirements.txt").read_text(encoding="utf-8") == "hand written\n"


def test_sync_all_covers_every_configured_version(env):
    result = CliRunner().invoke(cli, ["requirements", "sync", "--all"])
    assert result.exit_code == 0
    assert "v16" in result.output
    assert "v18" in result.output
