"""Tests for the requirements filesystem layer."""

import os

import pytest

from odoodev.core.requirements_sync import (
    SyncOutcome,
    ensure_generated_requirements,
    generated_path,
    overlay_path,
    seed_overlay,
    sync_allowed,
    sync_version,
)


class FakePaths:
    def __init__(self, native_dir):
        self.native_dir = native_dir


class FakeConfig:
    def __init__(self, native_dir):
        self.paths = FakePaths(native_dir)


@pytest.fixture
def cfg(tmp_path):
    return FakeConfig(str(tmp_path))


@pytest.fixture
def bundle(monkeypatch, tmp_path):
    """Point the baseline lookup at a controllable file."""
    base_file = tmp_path / "requirements.base.txt"
    base_file.write_text("Babel==2.16.0\nWerkzeug==3.1.3\n", encoding="utf-8")
    monkeypatch.setattr(
        "odoodev.core.requirements_sync.get_base_requirements_path",
        lambda version: base_file,
    )
    return base_file


def test_paths_sit_next_to_each_other(cfg):
    assert overlay_path(cfg).endswith("requirements.local.txt")
    assert generated_path(cfg).endswith("requirements.txt")
    assert os.path.dirname(overlay_path(cfg)) == os.path.dirname(generated_path(cfg))


def test_sync_allowed_on_a_fresh_environment(cfg):
    allowed, reason = sync_allowed(cfg)
    assert allowed is True
    assert reason == ""


def test_sync_blocked_on_a_hand_written_file_without_overlay(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\nmsal==1.31.0\n", encoding="utf-8")
    allowed, reason = sync_allowed(cfg)
    assert allowed is False
    assert "adopt" in reason


def test_sync_allowed_once_an_overlay_exists(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\n", encoding="utf-8")
    (tmp_path / "requirements.local.txt").write_text("msal==1.31.0\n", encoding="utf-8")
    allowed, _ = sync_allowed(cfg)
    assert allowed is True


def test_sync_allowed_on_a_previously_generated_file(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    allowed, _ = sync_allowed(cfg)
    assert allowed is True


def test_sync_writes_a_generated_file(cfg, tmp_path, bundle):
    (tmp_path / "requirements.local.txt").write_text("Werkzeug==3.0.6\n", encoding="utf-8")
    outcome = sync_version("16", cfg)
    assert outcome.written is True
    text = (tmp_path / "requirements.txt").read_text(encoding="utf-8")
    assert "GENERATED by odoodev" in text
    assert "Werkzeug==3.0.6" in text
    assert outcome.result.warnings


def test_check_only_never_writes_but_reports_staleness(cfg, tmp_path, bundle):
    outcome = sync_version("16", cfg, check_only=True)
    assert outcome.written is False
    assert outcome.stale is True
    assert not (tmp_path / "requirements.txt").exists()


def test_check_only_reports_current_after_a_sync(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    outcome = sync_version("16", cfg, check_only=True)
    assert outcome.stale is False


def test_sync_blocked_returns_reason_and_writes_nothing(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("hand written\n", encoding="utf-8")
    outcome = sync_version("16", cfg)
    assert outcome.written is False
    assert outcome.blocked_reason
    assert (tmp_path / "requirements.txt").read_text(encoding="utf-8") == "hand written\n"


def test_ensure_regenerates_when_the_bundle_moved_on(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    bundle.write_text("Babel==2.17.0\nWerkzeug==3.1.3\n", encoding="utf-8")
    outcome = ensure_generated_requirements("16", cfg)
    assert isinstance(outcome, SyncOutcome)
    assert outcome.written is True
    assert "2.17.0" in (tmp_path / "requirements.txt").read_text(encoding="utf-8")


def test_ensure_is_a_noop_when_the_file_is_current(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    assert ensure_generated_requirements("16", cfg) is None


def test_ensure_is_a_noop_on_a_hand_written_file(cfg, tmp_path, bundle):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\n", encoding="utf-8")
    assert ensure_generated_requirements("16", cfg) is None


def test_seed_overlay_creates_an_annotated_empty_file(cfg, tmp_path):
    assert seed_overlay(cfg) is True
    text = (tmp_path / "requirements.local.txt").read_text(encoding="utf-8")
    assert text.startswith("#")
    assert "requirements.local.txt" in text


def test_seed_overlay_never_overwrites(cfg, tmp_path):
    (tmp_path / "requirements.local.txt").write_text("msal==1.31.0\n", encoding="utf-8")
    assert seed_overlay(cfg) is False
    assert (tmp_path / "requirements.local.txt").read_text(encoding="utf-8") == "msal==1.31.0\n"
