"""Tests for the requirements filesystem layer."""

import os

import pytest

from odoodev.core.requirements_sync import (
    DiffRow,
    SyncOutcome,
    adopt_candidates,
    adopt_passthrough_lines,
    backup_existing,
    backup_overlay,
    bootstrap_requirements,
    ensure_generated_requirements,
    generated_path,
    installed_packages,
    overlay_has_content,
    overlay_path,
    seed_overlay,
    sync_allowed,
    sync_version,
    three_way_report,
    write_overlay,
)


class FakePaths:
    def __init__(self, native_dir):
        self.native_dir = native_dir


class FakeConfig:
    def __init__(self, native_dir):
        self.paths = FakePaths(native_dir)


@pytest.fixture
def cfg(tmp_path):
    return FakeConfig(str(tmp_path))


@pytest.fixture
def bundle(monkeypatch, tmp_path):
    """Point the baseline lookup at a controllable file."""
    base_file = tmp_path / "requirements.base.txt"
    base_file.write_text("Babel==2.16.0\nWerkzeug==3.1.3\n", encoding="utf-8")
    monkeypatch.setattr(
        "odoodev.core.requirements_sync.get_base_requirements_path",
        lambda version: base_file,
    )
    return base_file


def test_paths_sit_next_to_each_other(cfg):
    assert overlay_path(cfg).endswith("requirements.local.txt")
    assert generated_path(cfg).endswith("requirements.txt")
    assert os.path.dirname(overlay_path(cfg)) == os.path.dirname(generated_path(cfg))


def test_sync_allowed_on_a_fresh_environment(cfg):
    allowed, reason = sync_allowed(cfg)
    assert allowed is True
    assert reason == ""


def test_sync_blocked_on_a_hand_written_file_without_overlay(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\nmsal==1.31.0\n", encoding="utf-8")
    allowed, reason = sync_allowed(cfg)
    assert allowed is False
    assert "adopt" in reason


def test_sync_allowed_once_an_overlay_exists(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\n", encoding="utf-8")
    (tmp_path / "requirements.local.txt").write_text("msal==1.31.0\n", encoding="utf-8")
    allowed, _ = sync_allowed(cfg)
    assert allowed is True


def test_sync_allowed_on_a_previously_generated_file(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    allowed, _ = sync_allowed(cfg)
    assert allowed is True


def test_sync_writes_a_generated_file(cfg, tmp_path, bundle):
    (tmp_path / "requirements.local.txt").write_text("Werkzeug==3.0.6\n", encoding="utf-8")
    outcome = sync_version("16", cfg)
    assert outcome.written is True
    text = (tmp_path / "requirements.txt").read_text(encoding="utf-8")
    assert "GENERATED by odoodev" in text
    assert "Werkzeug==3.0.6" in text
    assert outcome.result.warnings


def test_check_only_never_writes_but_reports_staleness(cfg, tmp_path, bundle):
    outcome = sync_version("16", cfg, check_only=True)
    assert outcome.written is False
    assert outcome.stale is True
    assert not (tmp_path / "requirements.txt").exists()


def test_check_only_reports_current_after_a_sync(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    outcome = sync_version("16", cfg, check_only=True)
    assert outcome.stale is False


def test_sync_blocked_returns_reason_and_writes_nothing(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("hand written\n", encoding="utf-8")
    outcome = sync_version("16", cfg)
    assert outcome.written is False
    assert outcome.blocked_reason
    assert (tmp_path / "requirements.txt").read_text(encoding="utf-8") == "hand written\n"


def test_ensure_regenerates_when_the_bundle_moved_on(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    bundle.write_text("Babel==2.17.0\nWerkzeug==3.1.3\n", encoding="utf-8")
    outcome = ensure_generated_requirements("16", cfg)
    assert isinstance(outcome, SyncOutcome)
    assert outcome.written is True
    assert "2.17.0" in (tmp_path / "requirements.txt").read_text(encoding="utf-8")


def test_ensure_is_a_noop_when_the_file_is_current(cfg, tmp_path, bundle):
    sync_version("16", cfg)
    assert ensure_generated_requirements("16", cfg) is None


def test_ensure_is_a_noop_on_a_hand_written_file(cfg, tmp_path, bundle):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\n", encoding="utf-8")
    assert ensure_generated_requirements("16", cfg) is None


def test_seed_overlay_creates_an_annotated_empty_file(cfg, tmp_path):
    assert seed_overlay(cfg) is True
    text = (tmp_path / "requirements.local.txt").read_text(encoding="utf-8")
    assert text.startswith("#")
    assert "requirements.local.txt" in text


def test_seed_overlay_never_overwrites(cfg, tmp_path):
    (tmp_path / "requirements.local.txt").write_text("msal==1.31.0\n", encoding="utf-8")
    assert seed_overlay(cfg) is False
    assert (tmp_path / "requirements.local.txt").read_text(encoding="utf-8") == "msal==1.31.0\n"


def test_installed_packages_parses_uv_freeze(tmp_path, monkeypatch):
    import subprocess

    venv_dir = tmp_path / "venv"
    venv_dir.mkdir()
    (venv_dir / "pyvenv.cfg").write_text("home = /usr\n", encoding="utf-8")

    def fake_run(cmd, **kwargs):
        assert cmd[:3] == ["uv", "pip", "freeze"]
        return subprocess.CompletedProcess(cmd, 0, stdout="Babel==2.16.0\nWerkzeug==3.0.6\n", stderr="")

    monkeypatch.setattr("odoodev.core.requirements_sync.subprocess.run", fake_run)
    assert installed_packages(str(venv_dir)) == {"babel": "2.16.0", "werkzeug": "3.0.6"}


def test_installed_packages_returns_empty_on_failure(tmp_path, monkeypatch):
    import subprocess

    venv_dir = tmp_path / "venv"
    venv_dir.mkdir()
    (venv_dir / "pyvenv.cfg").write_text("home = /usr\n", encoding="utf-8")

    monkeypatch.setattr(
        "odoodev.core.requirements_sync.subprocess.run",
        lambda cmd, **kwargs: subprocess.CompletedProcess(cmd, 1, stdout="", stderr="boom"),
    )
    assert installed_packages(str(venv_dir)) == {}


def test_installed_packages_returns_empty_when_venv_missing(tmp_path):
    """uv pip freeze does not fail on a bogus VIRTUAL_ENV — it silently falls
    back to whatever environment uv can otherwise resolve and exits 0. So the
    guard must trigger on the venv's absence itself, before uv ever runs;
    this test exercises that path for real, without mocking subprocess.run.
    """
    missing_venv = tmp_path / "does-not-exist"
    assert installed_packages(str(missing_venv)) == {}


def test_installed_packages_returns_empty_when_uv_binary_missing(tmp_path, monkeypatch):
    venv_dir = tmp_path / "venv"
    venv_dir.mkdir()
    (venv_dir / "pyvenv.cfg").write_text("home = /usr\n", encoding="utf-8")

    def fake_run(cmd, **kwargs):
        raise FileNotFoundError("uv not found")

    monkeypatch.setattr("odoodev.core.requirements_sync.subprocess.run", fake_run)
    assert installed_packages(str(venv_dir)) == {}


def test_three_way_report_classifies_each_row(cfg, tmp_path, bundle, monkeypatch):
    (tmp_path / "requirements.local.txt").write_text("Werkzeug==3.0.6\nmsal==1.31.0\n", encoding="utf-8")
    monkeypatch.setattr(
        "odoodev.core.requirements_sync.installed_packages",
        lambda venv_dir: {"babel": "2.16.0", "werkzeug": "3.0.6"},
    )
    rows = {row.name: row for row in three_way_report("16", cfg)}

    assert rows["Babel"].status == "ok"
    assert rows["Werkzeug"].status == "local override"
    assert rows["Werkzeug"].base == "==3.1.3"
    assert rows["Werkzeug"].local == "==3.0.6"
    assert rows["Werkzeug"].installed == "3.0.6"
    assert rows["msal"].status == "local only"


def test_three_way_report_flags_declared_but_missing(cfg, tmp_path, bundle, monkeypatch):
    monkeypatch.setattr("odoodev.core.requirements_sync.installed_packages", lambda venv_dir: {})
    rows = {row.name: row for row in three_way_report("16", cfg)}
    assert rows["Babel"].status == "not installed"
    assert isinstance(rows["Babel"], DiffRow)


def test_adopt_candidates_split_conflicts_from_local_only(cfg, tmp_path, bundle):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\nWerkzeug==3.0.6\nmsal==1.31.0\n", encoding="utf-8")
    candidates = {c.existing.name: c for c in adopt_candidates("16", cfg)}

    assert "Babel" not in candidates  # identical to baseline, nothing to decide
    assert candidates["Werkzeug"].base is not None  # conflict: baseline has 3.1.3
    assert candidates["msal"].base is None  # local only


def test_adopt_candidates_respect_markers(cfg, tmp_path, monkeypatch):
    base_file = tmp_path / "base.txt"
    base_file.write_text("Babel==2.10.3 ; python_version < '3.13'\n", encoding="utf-8")
    monkeypatch.setattr("odoodev.core.requirements_sync.get_base_requirements_path", lambda version: base_file)
    (tmp_path / "requirements.txt").write_text(
        "Babel==2.10.3 ; python_version < '3.13'\nBabel==2.17.0 ; python_version >= '3.13'\n",
        encoding="utf-8",
    )
    candidates = adopt_candidates("16", cfg)
    assert len(candidates) == 1
    assert candidates[0].existing.marker == "python_version >= '3.13'"
    assert candidates[0].base is None


def test_adopt_passthrough_lines_collects_editable_vcs_and_url_requirements(cfg, tmp_path, bundle):
    (tmp_path / "requirements.txt").write_text(
        "Babel==2.16.0\n"
        "-e ./local-pkg\n"
        "git+https://example.invalid/x.git#egg=x\n"
        "pkg @ https://example.invalid/x.whl\n"
        "msal==1.31.0\n"
        "# a comment\n"
        "\n",
        encoding="utf-8",
    )
    lines = adopt_passthrough_lines(cfg)
    assert lines == [
        "-e ./local-pkg",
        "git+https://example.invalid/x.git#egg=x",
        "pkg @ https://example.invalid/x.whl",
    ]


def test_adopt_passthrough_lines_empty_on_a_plain_file(cfg, tmp_path, bundle):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\nmsal==1.31.0\n", encoding="utf-8")
    assert adopt_passthrough_lines(cfg) == []


def test_backup_existing_writes_pre_adopt_copy(cfg, tmp_path):
    (tmp_path / "requirements.txt").write_text("Babel==2.16.0\n", encoding="utf-8")
    path = backup_existing(cfg)
    assert path.endswith("requirements.txt.pre-adopt")
    assert (tmp_path / "requirements.txt.pre-adopt").read_text(encoding="utf-8") == "Babel==2.16.0\n"


def test_backup_existing_returns_none_without_a_file(cfg):
    assert backup_existing(cfg) is None


def test_overlay_has_content_false_when_missing(cfg):
    assert overlay_has_content(cfg) is False


def test_overlay_has_content_false_on_the_empty_seeded_template(cfg, tmp_path):
    seed_overlay(cfg)
    assert overlay_has_content(cfg) is False


def test_overlay_has_content_true_once_a_real_entry_is_present(cfg, tmp_path):
    seed_overlay(cfg)
    with open(overlay_path(cfg), "a", encoding="utf-8") as handle:
        handle.write("msal==1.31.0\n")
    assert overlay_has_content(cfg) is True


def test_backup_overlay_writes_pre_adopt_copy(cfg, tmp_path):
    (tmp_path / "requirements.local.txt").write_text("msal==1.31.0\n", encoding="utf-8")
    path = backup_overlay(cfg)
    assert path.endswith("requirements.local.txt.pre-adopt")
    assert (tmp_path / "requirements.local.txt.pre-adopt").read_text(encoding="utf-8") == "msal==1.31.0\n"


def test_backup_overlay_returns_none_without_a_file(cfg):
    assert backup_overlay(cfg) is None


def test_write_overlay_emits_parseable_entries(cfg, tmp_path):
    from odoodev.core.requirements_merge import parse_requirements

    existing = [
        line.requirement for line in parse_requirements("msal==1.31.0  # v16-microsoft365\n") if line.requirement
    ]
    path = write_overlay(cfg, existing)
    text = open(path, encoding="utf-8").read()
    assert "msal==1.31.0" in text
    assert "v16-microsoft365" in text
    assert text.lstrip().startswith("#")


def test_write_overlay_carries_passthrough_lines_verbatim(cfg, tmp_path):
    passthrough = [
        "-e ./local-pkg",
        "git+https://example.invalid/x.git#egg=x",
        "pkg @ https://example.invalid/x.whl",
    ]
    path = write_overlay(cfg, [], passthrough)
    text = open(path, encoding="utf-8").read()
    for line in passthrough:
        assert line in text


def test_bootstrap_seeds_overlay_and_generates(cfg, tmp_path, bundle):
    created, outcome = bootstrap_requirements("16", cfg)
    assert created is True
    assert outcome.written is True
    assert (tmp_path / "requirements.local.txt").exists()
    assert "GENERATED by odoodev" in (tmp_path / "requirements.txt").read_text(encoding="utf-8")


def test_bootstrap_keeps_an_existing_overlay(cfg, tmp_path, bundle):
    (tmp_path / "requirements.local.txt").write_text("msal==1.31.0\n", encoding="utf-8")
    created, outcome = bootstrap_requirements("16", cfg)
    assert created is False
    assert (tmp_path / "requirements.local.txt").read_text(encoding="utf-8") == "msal==1.31.0\n"
    assert "msal==1.31.0" in (tmp_path / "requirements.txt").read_text(encoding="utf-8")


def test_bootstrap_is_blocked_by_a_hand_written_file(cfg, tmp_path, bundle):
    (tmp_path / "requirements.txt").write_text("hand written\n", encoding="utf-8")
    created, outcome = bootstrap_requirements("16", cfg)
    assert outcome.blocked_reason
    assert (tmp_path / "requirements.txt").read_text(encoding="utf-8") == "hand written\n"
