"""Filesystem layer for the requirements base/overlay model.

Pure merging lives in requirements_merge; this module owns paths, the
overwrite guard and the write itself.
"""

from __future__ import annotations

import os
import subprocess
from dataclasses import dataclass

from odoodev import __version__
from odoodev.core.example_templates import get_base_requirements_path
from odoodev.core.requirements_merge import (
    MergeResult,
    extract_base_hash,
    is_generated,
    render_requirements,
    sha256_text,
)

OVERLAY_FILENAME = "requirements.local.txt"
GENERATED_FILENAME = "requirements.txt"

OVERLAY_TEMPLATE = """# requirements.local.txt — this file is yours; odoodev never overwrites it.
#
# Entries here replace the matching baseline entry (matched on package name AND
# environment marker) or are appended when the baseline has no counterpart.
# After editing, run: odoodev requirements sync
#
# Example:
#   Werkzeug==3.0.6   # MUST stay < 3.1: odoo/http.py:260 reads werkzeug.__version__
"""


@dataclass(frozen=True)
class SyncOutcome:
    """Result of a sync attempt for one version.

    `stale` says the rendered text differs from what is on disk. It is set in
    check_only mode too, which is what lets `sync --check` decide without
    rendering a second time.
    """

    version: str
    written: bool
    stale: bool
    path: str
    result: MergeResult | None
    blocked_reason: str


def overlay_path(version_cfg) -> str:
    """Path to the machine-local overlay file."""
    return os.path.join(version_cfg.paths.native_dir, OVERLAY_FILENAME)


def generated_path(version_cfg) -> str:
    """Path to the generated effective requirements file."""
    return os.path.join(version_cfg.paths.native_dir, GENERATED_FILENAME)


def _read(path: str) -> str:
    if not os.path.exists(path):
        return ""
    with open(path, encoding="utf-8") as handle:
        return handle.read()


def sync_allowed(version_cfg) -> tuple[bool, str]:
    """Decide whether sync may write over the existing requirements.txt.

    Refuses when a hand-maintained file is present and no overlay exists —
    otherwise sync would replace it with the bare baseline and lose every
    package that was never in the bundle. An overlay's existence counts as
    consent: the user has been through adopt.
    """
    target = generated_path(version_cfg)
    if not os.path.exists(target):
        return True, ""
    if is_generated(_read(target)):
        return True, ""
    if os.path.exists(overlay_path(version_cfg)):
        return True, ""
    return False, (
        f"{target} was not generated by odoodev and no {OVERLAY_FILENAME} exists. "
        f"Run 'odoodev requirements adopt' first — it preserves your current pins."
    )


def sync_version(version: str, version_cfg, *, check_only: bool = False) -> SyncOutcome:
    """Regenerate requirements.txt for one version."""
    target = generated_path(version_cfg)
    allowed, reason = sync_allowed(version_cfg)
    if not allowed:
        return SyncOutcome(version=version, written=False, stale=False, path=target, result=None, blocked_reason=reason)

    base_text = get_base_requirements_path(version).read_text(encoding="utf-8")
    local_text = _read(overlay_path(version_cfg))
    text, result = render_requirements(
        version=version,
        odoodev_version=__version__,
        base_text=base_text,
        local_text=local_text,
    )

    stale = text != _read(target)
    if check_only or not stale:
        written = False
    else:
        os.makedirs(os.path.dirname(target), exist_ok=True)
        with open(target, "w", encoding="utf-8") as handle:
            handle.write(text)
        written = True

    return SyncOutcome(version=version, written=written, stale=stale, path=target, result=result, blocked_reason="")


def ensure_generated_requirements(version: str, version_cfg) -> SyncOutcome | None:
    """Regenerate when the shipped baseline has moved on since the last sync.

    Returns None when nothing needed doing — which includes a hand-maintained
    file, so this never touches an environment that has not adopted yet.
    """
    target = generated_path(version_cfg)
    current = _read(target)
    if not current or not is_generated(current):
        return None

    base_file = get_base_requirements_path(version)
    if not base_file.is_file():
        return None
    if extract_base_hash(current) == sha256_text(base_file.read_text(encoding="utf-8")):
        return None

    outcome = sync_version(version, version_cfg)
    return outcome if outcome.written else None


def seed_overlay(version_cfg) -> bool:
    """Create an annotated empty overlay. Returns False if one already exists."""
    path = overlay_path(version_cfg)
    if os.path.exists(path):
        return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(OVERLAY_TEMPLATE)
    return True


@dataclass(frozen=True)
class DiffRow:
    """One package as seen by baseline, overlay and the installed venv."""

    name: str
    base: str
    local: str
    installed: str
    status: str


def installed_packages(venv_dir: str) -> dict[str, str]:
    """Canonical name → installed version, via `uv pip freeze`.

    Returns an empty mapping when the venv is absent or uv fails; the report
    then simply shows nothing as installed rather than aborting.

    `uv pip freeze` does NOT fail when VIRTUAL_ENV points at a non-existent
    path — it silently falls back to whatever Python environment uv can
    otherwise resolve and exits 0. So the venv's presence (a real
    pyvenv.cfg) is checked explicitly before ever invoking uv; without that
    check a version whose venv was never created would report an unrelated
    environment's packages instead of "not installed".
    """
    from odoodev.core.requirements_merge import canonical_name

    if not os.path.isfile(os.path.join(venv_dir, "pyvenv.cfg")):
        return {}

    env = {**os.environ, "VIRTUAL_ENV": venv_dir}
    try:
        result = subprocess.run(["uv", "pip", "freeze"], env=env, capture_output=True, text=True)
    except FileNotFoundError:
        return {}
    if result.returncode != 0:
        return {}

    packages: dict[str, str] = {}
    for line in result.stdout.splitlines():
        name, sep, version = line.strip().partition("==")
        if sep and name:
            packages[canonical_name(name)] = version.strip()
    return packages


def three_way_report(version: str, version_cfg) -> list[DiffRow]:
    """Compare baseline, overlay and installed packages for one version."""
    from odoodev.core.requirements_merge import parse_requirements

    base_text = get_base_requirements_path(version).read_text(encoding="utf-8")
    local_text = _read(overlay_path(version_cfg))
    installed = installed_packages(os.path.join(version_cfg.paths.native_dir, ".venv"))

    base_reqs = {
        line.requirement.merge_key: line.requirement
        for line in parse_requirements(base_text)
        if line.requirement is not None
    }
    local_reqs = {
        line.requirement.merge_key: line.requirement
        for line in parse_requirements(local_text)
        if line.requirement is not None
    }

    rows: list[DiffRow] = []
    for key in list(base_reqs) + [k for k in local_reqs if k not in base_reqs]:
        base_req = base_reqs.get(key)
        local_req = local_reqs.get(key)
        effective = local_req if local_req is not None else base_req
        if effective is None:  # unreachable: the key came from one of the two maps
            continue
        installed_version = installed.get(effective.key, "")

        if base_req is None:
            status = "local only"
        elif local_req is not None:
            status = "local override"
        elif not installed_version:
            status = "not installed"
        else:
            status = "ok"

        rows.append(
            DiffRow(
                name=effective.name,
                base=base_req.specifier if base_req else "",
                local=local_req.specifier if local_req else "",
                installed=installed_version,
                status=status,
            )
        )
    return rows
