"""Shell integration for odoodev (Fish/Bash/Zsh wrapper functions)."""

from __future__ import annotations

import os

from odoodev.core.environment import detect_shell

FISH_FUNCTION = """\
# odoodev shell integration
# Generated by: odoodev shell-setup
function odoodev-activate
    set -l _odoo_ver $argv[1]
    if test -z "$_odoo_ver"
        echo "Usage: odoodev-activate <version>" >&2
        return 1
    end
    set -l venv_dir (odoodev venv path $_odoo_ver)
    set -l env_dir (odoodev env dir $_odoo_ver)
    if test -d "$venv_dir"
        source "$venv_dir/bin/activate.fish"
        cd "$env_dir"
        echo "Activated Odoo v$_odoo_ver environment"
    else
        echo "No venv found for v$_odoo_ver. Run: odoodev venv setup $_odoo_ver" >&2
        return 1
    end
end

# Click shell completion for odoodev
function _odoodev_completion
    set -l response (env _ODOODEV_COMPLETE=fish_complete \\
        COMP_WORDS=(commandline -cp) \\
        COMP_CWORD=(commandline -t) odoodev 2>/dev/null)
    for completion in $response
        set -l metadata (string split "," -- $completion)
        if test (count $metadata) -ge 2
            if test $metadata[1] = "dir"
                __fish_complete_directories $metadata[2]
            else if test $metadata[1] = "file"
                __fish_complete_path $metadata[2]
            else if test $metadata[1] = "plain"
                echo $metadata[2]
            end
        end
    end
end
complete --no-files --command odoodev --arguments "(_odoodev_completion)"

# Version completions for odoodev-activate
complete --no-files --command odoodev-activate \\
    --arguments "(odoodev config versions --plain 2>/dev/null)" \\
    --description "Odoo version"

# Abbreviations for quick access
abbr -a --global oda 'odoodev-activate'
abbr -a --global odev 'odoodev'
"""

BASH_FUNCTION = """\
# odoodev shell integration
# Generated by: odoodev shell-setup
odoodev-activate() {
    local version="$1"
    if [ -z "$version" ]; then
        echo "Usage: odoodev-activate <version>" >&2
        return 1
    fi
    local venv_dir
    venv_dir=$(odoodev venv path "$version")
    local env_dir
    env_dir=$(odoodev env dir "$version")
    if [ -d "$venv_dir" ]; then
        source "$venv_dir/bin/activate"
        cd "$env_dir" || return
        echo "Activated Odoo v$version environment"
    else
        echo "No venv found for v$version. Run: odoodev venv setup $version" >&2
        return 1
    fi
}

# Click shell completion for odoodev
eval "$(_ODOODEV_COMPLETE=bash_source odoodev 2>/dev/null)"

# Version completions for odoodev-activate
_odoodev_activate_completions() {
    local versions
    versions=$(odoodev config versions --plain 2>/dev/null)
    COMPREPLY=($(compgen -W "$versions" -- "${COMP_WORDS[COMP_CWORD]}"))
}
complete -F _odoodev_activate_completions odoodev-activate

# Aliases for quick access
alias oda='odoodev-activate'
alias odev='odoodev'
"""

ZSH_FUNCTION = """\
# odoodev shell integration
# Generated by: odoodev shell-setup
odoodev-activate() {
    local version="$1"
    if [ -z "$version" ]; then
        echo "Usage: odoodev-activate <version>" >&2
        return 1
    fi
    local venv_dir
    venv_dir=$(odoodev venv path "$version")
    local env_dir
    env_dir=$(odoodev env dir "$version")
    if [ -d "$venv_dir" ]; then
        source "$venv_dir/bin/activate"
        cd "$env_dir" || return
        echo "Activated Odoo v$version environment"
    else
        echo "No venv found for v$version. Run: odoodev venv setup $version" >&2
        return 1
    fi
}

# Click shell completion for odoodev
eval "$(_ODOODEV_COMPLETE=zsh_source odoodev 2>/dev/null)"

# Version completions for odoodev-activate
_odoodev_activate_completions() {
    local versions
    versions=(${(f)"$(odoodev config versions --plain 2>/dev/null)"})
    compadd -a versions
}
compdef _odoodev_activate_completions odoodev-activate

# Aliases for quick access
alias oda='odoodev-activate'
alias odev='odoodev'
"""


def get_shell_config_path(shell: str | None = None) -> str:
    """Get the shell configuration file path.

    Args:
        shell: Shell type. Auto-detected if None.

    Returns:
        Path to shell config file.
    """
    if shell is None:
        shell = detect_shell()

    home = os.path.expanduser("~")
    if shell == "fish":
        return os.path.join(home, ".config", "fish", "conf.d", "odoodev.fish")
    elif shell == "zsh":
        return os.path.join(home, ".zshrc")
    else:
        return os.path.join(home, ".bashrc")


def get_shell_function(shell: str | None = None) -> str:
    """Get the shell function content for the given shell.

    Args:
        shell: Shell type. Auto-detected if None.

    Returns:
        Shell function code.
    """
    if shell is None:
        shell = detect_shell()

    if shell == "fish":
        return FISH_FUNCTION
    elif shell == "zsh":
        return ZSH_FUNCTION
    return BASH_FUNCTION


def install_shell_function(shell: str | None = None) -> str:
    """Install the odoodev shell function.

    For Fish: creates a separate file in conf.d/
    For Bash/Zsh: appends to .bashrc/.zshrc if not already present

    Args:
        shell: Shell type. Auto-detected if None.

    Returns:
        Path to the modified/created file.
    """
    if shell is None:
        shell = detect_shell()

    config_path = get_shell_config_path(shell)
    function_content = get_shell_function(shell)

    if shell == "fish":
        # Fish: create a separate file
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(function_content)
    else:
        # Bash/Zsh: check if already present, then append
        marker = "# odoodev shell integration"
        if os.path.exists(config_path):
            with open(config_path, encoding="utf-8") as f:
                content = f.read()
            if marker in content:
                # Already installed — replace existing block
                lines = content.split("\n")
                new_lines = []
                skip = False
                for line in lines:
                    if marker in line:
                        skip = True
                        continue
                    if skip and line.strip() == "}":
                        skip = False
                        continue
                    if not skip:
                        new_lines.append(line)
                content = "\n".join(new_lines)

        else:
            content = ""

        # Append function
        with open(config_path, "w", encoding="utf-8") as f:
            if content and not content.endswith("\n"):
                content += "\n"
            f.write(content)
            f.write("\n")
            f.write(function_content)

    return config_path
