"""Shell integration for odoodev (Fish/Bash/Zsh wrapper functions)."""

from __future__ import annotations

import os

from odoodev.core.environment import detect_shell

FISH_FUNCTION = """\
# odoodev shell integration
# Generated by: odoodev shell-setup
function odoodev-activate
    set -l version $argv[1]
    if test -z "$version"
        echo "Usage: odoodev-activate <version>" >&2
        return 1
    end
    set -l venv_dir (odoodev venv path $version)
    set -l env_dir (odoodev env dir $version)
    if test -d "$venv_dir"
        source "$venv_dir/bin/activate.fish"
        cd "$env_dir"
        echo "Activated Odoo v$version environment"
    else
        echo "No venv found for v$version. Run: odoodev venv setup $version" >&2
        return 1
    end
end
"""

BASH_FUNCTION = """\
# odoodev shell integration
# Generated by: odoodev shell-setup
odoodev-activate() {
    local version="$1"
    if [ -z "$version" ]; then
        echo "Usage: odoodev-activate <version>" >&2
        return 1
    fi
    local venv_dir
    venv_dir=$(odoodev venv path "$version")
    local env_dir
    env_dir=$(odoodev env dir "$version")
    if [ -d "$venv_dir" ]; then
        source "$venv_dir/bin/activate"
        cd "$env_dir" || return
        echo "Activated Odoo v$version environment"
    else
        echo "No venv found for v$version. Run: odoodev venv setup $version" >&2
        return 1
    fi
}
"""

ZSH_FUNCTION = BASH_FUNCTION  # Zsh is compatible with bash function syntax


def get_shell_config_path(shell: str | None = None) -> str:
    """Get the shell configuration file path.

    Args:
        shell: Shell type. Auto-detected if None.

    Returns:
        Path to shell config file.
    """
    if shell is None:
        shell = detect_shell()

    home = os.path.expanduser("~")
    if shell == "fish":
        return os.path.join(home, ".config", "fish", "conf.d", "odoodev.fish")
    elif shell == "zsh":
        return os.path.join(home, ".zshrc")
    else:
        return os.path.join(home, ".bashrc")


def get_shell_function(shell: str | None = None) -> str:
    """Get the shell function content for the given shell.

    Args:
        shell: Shell type. Auto-detected if None.

    Returns:
        Shell function code.
    """
    if shell is None:
        shell = detect_shell()

    if shell == "fish":
        return FISH_FUNCTION
    elif shell == "zsh":
        return ZSH_FUNCTION
    return BASH_FUNCTION


def install_shell_function(shell: str | None = None) -> str:
    """Install the odoodev shell function.

    For Fish: creates a separate file in conf.d/
    For Bash/Zsh: appends to .bashrc/.zshrc if not already present

    Args:
        shell: Shell type. Auto-detected if None.

    Returns:
        Path to the modified/created file.
    """
    if shell is None:
        shell = detect_shell()

    config_path = get_shell_config_path(shell)
    function_content = get_shell_function(shell)

    if shell == "fish":
        # Fish: create a separate file
        os.makedirs(os.path.dirname(config_path), exist_ok=True)
        with open(config_path, "w", encoding="utf-8") as f:
            f.write(function_content)
    else:
        # Bash/Zsh: check if already present, then append
        marker = "# odoodev shell integration"
        if os.path.exists(config_path):
            with open(config_path, encoding="utf-8") as f:
                content = f.read()
            if marker in content:
                # Already installed — replace existing block
                lines = content.split("\n")
                new_lines = []
                skip = False
                for line in lines:
                    if marker in line:
                        skip = True
                        continue
                    if skip and line.strip() == "}":
                        skip = False
                        continue
                    if not skip:
                        new_lines.append(line)
                content = "\n".join(new_lines)

        else:
            content = ""

        # Append function
        with open(config_path, "w", encoding="utf-8") as f:
            if content and not content.endswith("\n"):
                content += "\n"
            f.write(content)
            f.write("\n")
            f.write(function_content)

    return config_path
